// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/Content/Accordion.tsx";
import * as $$$$$$2 from "./sections/Content/AnimatedInfoCard.tsx";
import * as $$$$$$3 from "./sections/Content/ColoredInfoCard.tsx";
import * as $$$$$$4 from "./sections/Content/MentorExplanation.tsx";
import * as $$$$$$5 from "./sections/Content/MentorReview.tsx";
import * as $$$$$$6 from "./sections/Content/Newsletter.tsx";
import * as $$$$$$7 from "./sections/Content/PartnersList.tsx";
import * as $$$$$$8 from "./sections/Content/Reports.tsx";
import * as $$$$$$9 from "./sections/Content/StudentReview.tsx";
import * as $$$$$$10 from "./sections/Faq.tsx";
import * as $$$$$$11 from "./sections/Footer.tsx";
import * as $$$$$$12 from "./sections/Header.tsx";
import * as $$$$$$35 from "./sections/hero-1.tsx";
import * as $$$$$$36 from "./sections/hero-2.tsx";
import * as $$$$$$13 from "./sections/Hero.tsx";
import * as $$$$$$37 from "./sections/hero2.tsx";
import * as $$$$$$14 from "./sections/Image/BannerText.tsx";
import * as $$$$$$15 from "./sections/Image/GridBanner.tsx";
import * as $$$$$$16 from "./sections/Image/Media.tsx";
import * as $$$$$$17 from "./sections/Image/Parallax.tsx";
import * as $$$$$$18 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$19 from "./sections/Logos.tsx";
import * as $$$$$$20 from "./sections/Page404/Page404.tsx";
import * as $$$$$$21 from "./sections/Slider/BiographySlider.tsx";
import * as $$$$$$22 from "./sections/Slider/ClassesSlider.tsx";
import * as $$$$$$23 from "./sections/Slider/PartnerSlider.tsx";
import * as $$$$$$24 from "./sections/Slider/PartnersListMobile.tsx";
import * as $$$$$$25 from "./sections/Slider/SliderInfoCard.tsx";
import * as $$$$$$26 from "./sections/Testimonials.tsx";
import * as $$$$$$27 from "./sections/Text/DonateDisclaimer.tsx";
import * as $$$$$$28 from "./sections/Text/Investment.tsx";
import * as $$$$$$29 from "./sections/Text/MentoringDisclaimer.tsx";
import * as $$$$$$30 from "./sections/Text/QuantityHighlight.tsx";
import * as $$$$$$31 from "./sections/Text/Quote.tsx";
import * as $$$$$$32 from "./sections/Text/RichText.tsx";
import * as $$$$$$33 from "./sections/Text/TextCard.tsx";
import * as $$$$$$34 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/Content/Accordion.tsx": $$$$$$1,
    "site/sections/Content/AnimatedInfoCard.tsx": $$$$$$2,
    "site/sections/Content/ColoredInfoCard.tsx": $$$$$$3,
    "site/sections/Content/MentorExplanation.tsx": $$$$$$4,
    "site/sections/Content/MentorReview.tsx": $$$$$$5,
    "site/sections/Content/Newsletter.tsx": $$$$$$6,
    "site/sections/Content/PartnersList.tsx": $$$$$$7,
    "site/sections/Content/Reports.tsx": $$$$$$8,
    "site/sections/Content/StudentReview.tsx": $$$$$$9,
    "site/sections/Faq.tsx": $$$$$$10,
    "site/sections/Footer.tsx": $$$$$$11,
    "site/sections/Header.tsx": $$$$$$12,
    "site/sections/hero-1.tsx": $$$$$$35,
    "site/sections/hero-2.tsx": $$$$$$36,
    "site/sections/Hero.tsx": $$$$$$13,
    "site/sections/hero2.tsx": $$$$$$37,
    "site/sections/Image/BannerText.tsx": $$$$$$14,
    "site/sections/Image/GridBanner.tsx": $$$$$$15,
    "site/sections/Image/Media.tsx": $$$$$$16,
    "site/sections/Image/Parallax.tsx": $$$$$$17,
    "site/sections/ImageWithParagraph.tsx": $$$$$$18,
    "site/sections/Logos.tsx": $$$$$$19,
    "site/sections/Page404/Page404.tsx": $$$$$$20,
    "site/sections/Slider/BiographySlider.tsx": $$$$$$21,
    "site/sections/Slider/ClassesSlider.tsx": $$$$$$22,
    "site/sections/Slider/PartnerSlider.tsx": $$$$$$23,
    "site/sections/Slider/PartnersListMobile.tsx": $$$$$$24,
    "site/sections/Slider/SliderInfoCard.tsx": $$$$$$25,
    "site/sections/Testimonials.tsx": $$$$$$26,
    "site/sections/Text/DonateDisclaimer.tsx": $$$$$$27,
    "site/sections/Text/Investment.tsx": $$$$$$28,
    "site/sections/Text/MentoringDisclaimer.tsx": $$$$$$29,
    "site/sections/Text/QuantityHighlight.tsx": $$$$$$30,
    "site/sections/Text/Quote.tsx": $$$$$$31,
    "site/sections/Text/RichText.tsx": $$$$$$32,
    "site/sections/Text/TextCard.tsx": $$$$$$33,
    "site/sections/Theme/Theme.tsx": $$$$$$34,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
