// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BlogPosts.tsx";
import * as $$$$$$1 from "./sections/Content/Newsletter.tsx";
import * as $$$$$$2 from "./sections/Content/PartnersList.tsx";
import * as $$$$$$3 from "./sections/Content/Reports.tsx";
import * as $$$$$$4 from "./sections/Faq.tsx";
import * as $$$$$$5 from "./sections/Footer.tsx";
import * as $$$$$$6 from "./sections/Header.tsx";
import * as $$$$$$15 from "./sections/hero-1.tsx";
import * as $$$$$$16 from "./sections/hero-2.tsx";
import * as $$$$$$7 from "./sections/Hero.tsx";
import * as $$$$$$17 from "./sections/hero2.tsx";
import * as $$$$$$9 from "./sections/Image/BannerText.tsx";
import * as $$$$$$10 from "./sections/Image/GridBanner.tsx";
import * as $$$$$$8 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$11 from "./sections/Logos.tsx";
import * as $$$$$$12 from "./sections/Slider/ClassesSlider.tsx";
import * as $$$$$$13 from "./sections/Testimonials.tsx";
import * as $$$$$$14 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/BlogPosts.tsx": $$$$$$0,
    "site/sections/Content/Newsletter.tsx": $$$$$$1,
    "site/sections/Content/PartnersList.tsx": $$$$$$2,
    "site/sections/Content/Reports.tsx": $$$$$$3,
    "site/sections/Faq.tsx": $$$$$$4,
    "site/sections/Footer.tsx": $$$$$$5,
    "site/sections/Header.tsx": $$$$$$6,
    "site/sections/hero-1.tsx": $$$$$$15,
    "site/sections/hero-2.tsx": $$$$$$16,
    "site/sections/Hero.tsx": $$$$$$7,
    "site/sections/hero2.tsx": $$$$$$17,
    "site/sections/Image/BannerText.tsx": $$$$$$9,
    "site/sections/Image/GridBanner.tsx": $$$$$$10,
    "site/sections/ImageWithParagraph.tsx": $$$$$$8,
    "site/sections/Logos.tsx": $$$$$$11,
    "site/sections/Slider/ClassesSlider.tsx": $$$$$$12,
    "site/sections/Testimonials.tsx": $$$$$$13,
    "site/sections/Theme/Theme.tsx": $$$$$$14,
  },
  "apps": {
    "site/apps/decohub.ts": $$$$$$$$$$$0,
    "site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
